export const season = [
  { id: "invita", title: "El primer mensaje" },
  { id: "colonia", title: "El portón" },
  { id: "cancela", title: "La casa se cae" },
  { id: "abre", title: "La Colmena" },
  { id: "voces", title: "Quién es quién" },
  { id: "amigo", title: "Rafael" },
  { id: "ruido", title: "La cadena" },
  { id: "sale", title: "La esquina" },
  { id: "silencio", title: "Deja de escribir" },
  { id: "manana", title: "Al día siguiente" },
  { id: "versiones", title: "Horas que se mueven" },
  { id: "secretos", title: "Lo que no es del grupo" },
  { id: "ruptura", title: "La deuda" },
  { id: "presion", title: "La cadena nueva" },
  { id: "verdad", title: "El Nene" },
  { id: "rescate", title: "El cuarto" },
  { id: "despues", title: "Mateo habla" },
  { id: "epilogo", title: "La inicial C" },
];
